$background = rgb(0B1118)
$color0     = rgb(0B1118)
$color1     = rgb(295C4E)
$color2     = rgb(314C51)
$color3     = rgb(50635E)
$color4     = rgb(6B7375)
$color5     = rgb(678C54)
$color6     = rgb(808F71)
$color7     = rgb(c6c9c7)
$color8     = rgb(8a8c8b)
$color9     = rgb(295C4E)
$color10    = rgb(314C51)
$color11    = rgb(50635E)
$color12    = rgb(6B7375)
$color13    = rgb(678C54)
$color14    = rgb(808F71)
$color15    = rgb(c6c9c7)

