$background = rgb(090909)
$color0     = rgb(090909)
$color1     = rgb(746957)
$color2     = rgb(797163)
$color3     = rgb(84765D)
$color4     = rgb(8A7B62)
$color5     = rgb(988668)
$color6     = rgb(AC9772)
$color7     = rgb(d2c7b4)
$color8     = rgb(938b7d)
$color9     = rgb(746957)
$color10    = rgb(797163)
$color11    = rgb(84765D)
$color12    = rgb(8A7B62)
$color13    = rgb(988668)
$color14    = rgb(AC9772)
$color15    = rgb(d2c7b4)

