$background = rgb(371720)
$color0     = rgb(371720)
$color1     = rgb(8DA350)
$color2     = rgb(397788)
$color3     = rgb(289BA5)
$color4     = rgb(5497A5)
$color5     = rgb(27BAC6)
$color6     = rgb(1CC5D6)
$color7     = rgb(87d7dc)
$color8     = rgb(5e969a)
$color9     = rgb(8DA350)
$color10    = rgb(397788)
$color11    = rgb(289BA5)
$color12    = rgb(5497A5)
$color13    = rgb(27BAC6)
$color14    = rgb(1CC5D6)
$color15    = rgb(87d7dc)

