foreground   #9eaac2
background   #0A060D
cursor       #9eaac2

color0       #0A060D
color8       #6e7687
color1       #2C306F
color9       #2C306F
color2       #4C366E
color10      #4C366E
color3       #434971
color11      #434971
color4       #3B3383
color12      #3B3383
color5       #473787
color13      #473787
color6       #3B5D8E
color14      #3B5D8E
color7       #9eaac2
color15      #9eaac2
